[project]
name = "reproducible-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andrea Raaschou", email = "andrea.raaschou@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "notebook>=7.6.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pooch>=1.9.0",
    "scipy>=1.18.1",
]

[project.scripts]
reproducible-workflow = "reproducible_workflow:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
